/// Metadata for SQLite functions that NodeQL can render through the generic
/// function reporter. The catalog intentionally follows SQLite's official
/// core, date/time, and aggregate function references. `load_extension` is
/// deliberately excluded: a visual database workspace must not be able to
/// load arbitrary native libraries.
enum SqliteFunctionCategory { core, dateTime, aggregate }

class SqliteFunctionSignature {
  const SqliteFunctionSignature({
    required this.name,
    required this.category,
    this.minArgs = 0,
    this.maxArgs,
    this.argumentHints = const <String>[],
    this.templateArguments = const <String>[],
    this.versionOrBuildDependent = false,
  });

  final String name;
  final SqliteFunctionCategory category;
  final int minArgs;
  final int? maxArgs;
  final List<String> argumentHints;
  final List<String> templateArguments;
  final bool versionOrBuildDependent;

  bool acceptsArity(int count) =>
      count >= minArgs && (maxArgs == null || count <= maxArgs!);
}

const sqliteFunctionCatalog = <SqliteFunctionSignature>[
  // Core scalar functions.
  SqliteFunctionSignature(
    name: 'abs',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['value'],
    templateArguments: ['value'],
  ),
  SqliteFunctionSignature(
    name: 'changes',
    category: SqliteFunctionCategory.core,
  ),
  SqliteFunctionSignature(
    name: 'char',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    argumentHints: ['code point'],
    templateArguments: ['65'],
  ),
  SqliteFunctionSignature(
    name: 'coalesce',
    category: SqliteFunctionCategory.core,
    minArgs: 2,
    argumentHints: ['value'],
    templateArguments: ['first_value', 'fallback'],
  ),
  SqliteFunctionSignature(
    name: 'concat',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    argumentHints: ['value'],
    templateArguments: ["'Hello'", "' world'"],
  ),
  SqliteFunctionSignature(
    name: 'concat_ws',
    category: SqliteFunctionCategory.core,
    minArgs: 2,
    argumentHints: ['separator', 'value'],
    templateArguments: ["', '", 'first_value', 'second_value'],
    versionOrBuildDependent: true,
  ),
  SqliteFunctionSignature(
    name: 'format',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    argumentHints: ['format', 'value'],
    templateArguments: ["'%s'", 'value'],
  ),
  SqliteFunctionSignature(
    name: 'glob',
    category: SqliteFunctionCategory.core,
    minArgs: 2,
    maxArgs: 2,
    argumentHints: ['pattern', 'value'],
    templateArguments: ["'*.txt'", 'name'],
  ),
  SqliteFunctionSignature(
    name: 'hex',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['value'],
    templateArguments: ['value'],
  ),
  SqliteFunctionSignature(
    name: 'if',
    category: SqliteFunctionCategory.core,
    minArgs: 2,
    argumentHints: ['condition', 'value'],
    templateArguments: ['condition', 'true_value', 'false_value'],
    versionOrBuildDependent: true,
  ),
  SqliteFunctionSignature(
    name: 'ifnull',
    category: SqliteFunctionCategory.core,
    minArgs: 2,
    maxArgs: 2,
    argumentHints: ['value', 'fallback'],
    templateArguments: ['value', 'fallback'],
  ),
  SqliteFunctionSignature(
    name: 'iif',
    category: SqliteFunctionCategory.core,
    minArgs: 2,
    argumentHints: ['condition', 'value'],
    templateArguments: ['condition', 'true_value', 'false_value'],
  ),
  SqliteFunctionSignature(
    name: 'instr',
    category: SqliteFunctionCategory.core,
    minArgs: 2,
    maxArgs: 2,
    argumentHints: ['text', 'needle'],
    templateArguments: ['text', "'find me'"],
  ),
  SqliteFunctionSignature(
    name: 'last_insert_rowid',
    category: SqliteFunctionCategory.core,
  ),
  SqliteFunctionSignature(
    name: 'length',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['value'],
    templateArguments: ['value'],
  ),
  SqliteFunctionSignature(
    name: 'like',
    category: SqliteFunctionCategory.core,
    minArgs: 2,
    maxArgs: 3,
    argumentHints: ['pattern', 'value', 'escape'],
    templateArguments: ["'%text%'", 'value'],
  ),
  SqliteFunctionSignature(
    name: 'likelihood',
    category: SqliteFunctionCategory.core,
    minArgs: 2,
    maxArgs: 2,
    argumentHints: ['condition', 'probability'],
    templateArguments: ['condition', '0.5'],
  ),
  SqliteFunctionSignature(
    name: 'likely',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['condition'],
    templateArguments: ['condition'],
  ),
  SqliteFunctionSignature(
    name: 'lower',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['text'],
    templateArguments: ['text'],
  ),
  SqliteFunctionSignature(
    name: 'ltrim',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 2,
    argumentHints: ['text', 'characters'],
    templateArguments: ['text'],
  ),
  SqliteFunctionSignature(
    name: 'nullif',
    category: SqliteFunctionCategory.core,
    minArgs: 2,
    maxArgs: 2,
    argumentHints: ['value', 'compare'],
    templateArguments: ['value', 'compare'],
  ),
  SqliteFunctionSignature(
    name: 'octet_length',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['value'],
    templateArguments: ['value'],
    versionOrBuildDependent: true,
  ),
  SqliteFunctionSignature(
    name: 'printf',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    argumentHints: ['format', 'value'],
    templateArguments: ["'%s'", 'value'],
  ),
  SqliteFunctionSignature(
    name: 'quote',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['value'],
    templateArguments: ['value'],
  ),
  SqliteFunctionSignature(
    name: 'random',
    category: SqliteFunctionCategory.core,
  ),
  SqliteFunctionSignature(
    name: 'randomblob',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['bytes'],
    templateArguments: ['16'],
  ),
  SqliteFunctionSignature(
    name: 'replace',
    category: SqliteFunctionCategory.core,
    minArgs: 3,
    maxArgs: 3,
    argumentHints: ['text', 'from', 'to'],
    templateArguments: ['text', "'old'", "'new'"],
  ),
  SqliteFunctionSignature(
    name: 'round',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 2,
    argumentHints: ['value', 'digits'],
    templateArguments: ['value', '2'],
  ),
  SqliteFunctionSignature(
    name: 'rtrim',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 2,
    argumentHints: ['text', 'characters'],
    templateArguments: ['text'],
  ),
  SqliteFunctionSignature(
    name: 'sign',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['value'],
    templateArguments: ['value'],
    versionOrBuildDependent: true,
  ),
  SqliteFunctionSignature(
    name: 'soundex',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['text'],
    templateArguments: ['name'],
    versionOrBuildDependent: true,
  ),
  SqliteFunctionSignature(
    name: 'sqlite_compileoption_get',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['index'],
    templateArguments: ['0'],
  ),
  SqliteFunctionSignature(
    name: 'sqlite_compileoption_used',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['option'],
    templateArguments: ["'ENABLE_FTS5'"],
  ),
  SqliteFunctionSignature(
    name: 'sqlite_offset',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['column'],
    templateArguments: ['column'],
    versionOrBuildDependent: true,
  ),
  SqliteFunctionSignature(
    name: 'sqlite_source_id',
    category: SqliteFunctionCategory.core,
  ),
  SqliteFunctionSignature(
    name: 'sqlite_version',
    category: SqliteFunctionCategory.core,
  ),
  SqliteFunctionSignature(
    name: 'substr',
    category: SqliteFunctionCategory.core,
    minArgs: 2,
    maxArgs: 3,
    argumentHints: ['text', 'start', 'length'],
    templateArguments: ['text', '1', '3'],
  ),
  SqliteFunctionSignature(
    name: 'substring',
    category: SqliteFunctionCategory.core,
    minArgs: 2,
    maxArgs: 3,
    argumentHints: ['text', 'start', 'length'],
    templateArguments: ['text', '1', '3'],
  ),
  SqliteFunctionSignature(
    name: 'total_changes',
    category: SqliteFunctionCategory.core,
  ),
  SqliteFunctionSignature(
    name: 'trim',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 2,
    argumentHints: ['text', 'characters'],
    templateArguments: ['text'],
  ),
  SqliteFunctionSignature(
    name: 'typeof',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['value'],
    templateArguments: ['value'],
  ),
  SqliteFunctionSignature(
    name: 'unhex',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 2,
    argumentHints: ['text', 'ignore'],
    templateArguments: ['hex_text'],
    versionOrBuildDependent: true,
  ),
  SqliteFunctionSignature(
    name: 'unicode',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['text'],
    templateArguments: ['text'],
  ),
  SqliteFunctionSignature(
    name: 'unistr',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['text'],
    templateArguments: ["'\\u0041'"],
    versionOrBuildDependent: true,
  ),
  SqliteFunctionSignature(
    name: 'unistr_quote',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['value'],
    templateArguments: ['value'],
    versionOrBuildDependent: true,
  ),
  SqliteFunctionSignature(
    name: 'unlikely',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['condition'],
    templateArguments: ['condition'],
  ),
  SqliteFunctionSignature(
    name: 'upper',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['text'],
    templateArguments: ['text'],
  ),
  SqliteFunctionSignature(
    name: 'zeroblob',
    category: SqliteFunctionCategory.core,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['bytes'],
    templateArguments: ['16'],
  ),

  // Date and time functions.
  SqliteFunctionSignature(
    name: 'date',
    category: SqliteFunctionCategory.dateTime,
    minArgs: 0,
    argumentHints: ['time value', 'modifier'],
    templateArguments: ["'now'"],
  ),
  SqliteFunctionSignature(
    name: 'time',
    category: SqliteFunctionCategory.dateTime,
    minArgs: 0,
    argumentHints: ['time value', 'modifier'],
    templateArguments: ["'now'"],
  ),
  SqliteFunctionSignature(
    name: 'datetime',
    category: SqliteFunctionCategory.dateTime,
    minArgs: 0,
    argumentHints: ['time value', 'modifier'],
    templateArguments: ['unix_timestamp', "'unixepoch'"],
  ),
  SqliteFunctionSignature(
    name: 'julianday',
    category: SqliteFunctionCategory.dateTime,
    minArgs: 0,
    argumentHints: ['time value', 'modifier'],
    templateArguments: ["'now'"],
  ),
  SqliteFunctionSignature(
    name: 'unixepoch',
    category: SqliteFunctionCategory.dateTime,
    minArgs: 0,
    argumentHints: ['time value', 'modifier'],
    templateArguments: ["'now'"],
  ),
  SqliteFunctionSignature(
    name: 'strftime',
    category: SqliteFunctionCategory.dateTime,
    minArgs: 1,
    argumentHints: ['format', 'time value', 'modifier'],
    templateArguments: ["'%F %T'", "'now'"],
  ),
  SqliteFunctionSignature(
    name: 'timediff',
    category: SqliteFunctionCategory.dateTime,
    minArgs: 2,
    maxArgs: 2,
    argumentHints: ['time A', 'time B'],
    templateArguments: ["'now'", "'2020-01-01'"],
  ),

  // Aggregate functions, including SQLite's optional percentile extension.
  SqliteFunctionSignature(
    name: 'avg',
    category: SqliteFunctionCategory.aggregate,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['value'],
    templateArguments: ['value'],
  ),
  SqliteFunctionSignature(
    name: 'count',
    category: SqliteFunctionCategory.aggregate,
    minArgs: 0,
    maxArgs: 1,
    argumentHints: ['value'],
    templateArguments: ['*'],
  ),
  SqliteFunctionSignature(
    name: 'group_concat',
    category: SqliteFunctionCategory.aggregate,
    minArgs: 1,
    maxArgs: 2,
    argumentHints: ['value', 'separator'],
    templateArguments: ['value', "', '"],
  ),
  SqliteFunctionSignature(
    name: 'max',
    category: SqliteFunctionCategory.aggregate,
    minArgs: 1,
    argumentHints: ['value'],
    templateArguments: ['value'],
  ),
  SqliteFunctionSignature(
    name: 'median',
    category: SqliteFunctionCategory.aggregate,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['value'],
    templateArguments: ['value'],
    versionOrBuildDependent: true,
  ),
  SqliteFunctionSignature(
    name: 'min',
    category: SqliteFunctionCategory.aggregate,
    minArgs: 1,
    argumentHints: ['value'],
    templateArguments: ['value'],
  ),
  SqliteFunctionSignature(
    name: 'percentile',
    category: SqliteFunctionCategory.aggregate,
    minArgs: 2,
    maxArgs: 2,
    argumentHints: ['value', 'percent'],
    templateArguments: ['value', '50'],
    versionOrBuildDependent: true,
  ),
  SqliteFunctionSignature(
    name: 'percentile_cont',
    category: SqliteFunctionCategory.aggregate,
    minArgs: 2,
    maxArgs: 2,
    argumentHints: ['value', 'fraction'],
    templateArguments: ['value', '0.5'],
    versionOrBuildDependent: true,
  ),
  SqliteFunctionSignature(
    name: 'percentile_disc',
    category: SqliteFunctionCategory.aggregate,
    minArgs: 2,
    maxArgs: 2,
    argumentHints: ['value', 'fraction'],
    templateArguments: ['value', '0.5'],
    versionOrBuildDependent: true,
  ),
  SqliteFunctionSignature(
    name: 'string_agg',
    category: SqliteFunctionCategory.aggregate,
    minArgs: 2,
    maxArgs: 2,
    argumentHints: ['value', 'separator'],
    templateArguments: ['value', "', '"],
    versionOrBuildDependent: true,
  ),
  SqliteFunctionSignature(
    name: 'sum',
    category: SqliteFunctionCategory.aggregate,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['value'],
    templateArguments: ['value'],
  ),
  SqliteFunctionSignature(
    name: 'total',
    category: SqliteFunctionCategory.aggregate,
    minArgs: 1,
    maxArgs: 1,
    argumentHints: ['value'],
    templateArguments: ['value'],
  ),
];

SqliteFunctionSignature? sqliteFunctionByName(String name) {
  final normalized = name.trim().toLowerCase();
  for (final signature in sqliteFunctionCatalog) {
    if (signature.name == normalized) return signature;
  }
  return null;
}
